package/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage, name="home"),
    path('about/', views.About, name="about"),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="feed"),
    path('create/', views.create_post, name="create-post"),
    path('<slug:slug>', views.post, name="post" )
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.register, name="register" ),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout")
]

posts/models.py
from django.db import models

class Post(models.Model):
    title=models.CharField(max_length=75)
    body=models.TextField()
    slug=models.SlugField()
    date=models.DateTimeField(auto_now_add=True)
    banner=models.ImageField(default='fallback.jpg', blank=True)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

package/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def HomePage(request):
    # return HttpResponse("This is HomePage")
    return render(request, 'home.html')

def About(request):
    # return HttpResponse("This is about page")
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import models

# Create your views here.
def posts_list(request):
    posts = models.Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})

def post(request, slug):
    post = models.Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html',{'post': post})

@login_required(login_url="/users/login")
def create_post(request):
    return render(request, 'posts/post_new.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout

# Create your views here.
def register(request):
    if request.method=="POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            auth_login(request, form.save())
            return redirect("posts:feed")    
    else:
        form = UserCreationForm();        
    return render(request, 'users/register.html', {'form': form})

def login(request):
    if request.method=="POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("posts:feed")    
    else:
        form = AuthenticationForm();        
    return render(request, 'users/login.html', {'form': form})

def logout(request):
    if request.method == "POST":
        auth_logout(request)
        return redirect("posts:feed")

posts/templates/posts/post_new.html
{% extends "layout.html" %} 

{% block title %} 
    New Post 
{% endblock title %} 

{%block content %}
    <article class="post">
        <h1>New Post</h1>
    </article>
{% endblock %}

posts/templates/posts/post_page.html
{% extends "layout.html" %} 

{% block title %} 
    {{post.title}}
{% endblock title %} 

{%block content %}
    <article class="post">
        <img class="banner" src={{post.banner.url}} alt={{post.title}} />
        <h2>{{post.title}}</h2>
        <p>{{post.date}}</p>
        <p>{{post.body}}</p>
    </article>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends "layout.html" %} 

{% block title %} 
    Posts 
{% endblock title %} 

{%block content %}
    <h1>Posts List</h1>
    {%for post in posts%}
    <article class="post">
    <h2>
        <a href={% url "posts:post" slug=post.slug%}> {{post.title}} </a>
    </h2>
    <p>{{post.date}}</p>
    <p>{{post.body}}</p>
    </article>
    {% endfor %} 
{% endblock %}

templates/about.html
{% extends "layout.html" %}

{% block title %}
    Home Page
{% endblock title %}

{% block content %}
    <h1>This is my AboutPage</h1>
    <h3>Checkout my  <a href="/">home</a> page </h3>
{% endblock  %}

templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home Page
{% endblock title %}

{% block content %}
    <h1>This is my HomePage</h1>
    <h3>Checkout my  <a href="/about">about</a> page </h3>
{% endblock  %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src={%static "js/script.js"%} defer></script>
    <title>
    {%block title%}
        Default title
    {% endblock %}
    </title>
</head>
<body>
    <nav>
        <a href={% url "home" %} >🏠</a> | 
        <a href= {% url "about" %}>😀</a> | 
        <a href= {% url "posts:feed" %}>📰</a>
        <a href= {% url "users:register" %}>🔒</a>
        <a href= {% url "users:login" %}>🔐</a>
        <form class="logout" action={% url "users:logout" %} method="post">
            {% csrf_token %}
            <button class="logout-button" title="logout" aria-label="user logout">👋</button>
        </form>
        <a href= {% url "posts:create-post" %}>🆕</a>
    </nav>
    <main>
        {% block content %}
            Deafult content
        {% endblock %}
    </main>
</body>
</html>

users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
    login
{% endblock  %}

{% block content %}
    <h1>Login user</h1>
    <form method="post" action="/users/login/">
        {% csrf_token %}
        {{form}}
        <button>submit</button>
    </form>
{% endblock  %}

users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
    register
{% endblock  %}

{% block content %}
    <h1>Register user</h1>
    <form method="post" action="/users/register/">
        {% csrf_token %}
        {{form}}
        <button>submit</button>
    </form>
{% endblock  %}